sudo: required

language: go

services:
  - docker

before_install:
- sudo apt-get update
- sudo apt-get install python2.7
- docker pull mongo

install:
- cd $TRAVIS_BUILD_DIR
- export PATH=$PATH:$TRAVIS_BUILD_DIR/bin/
- go get ./...
- cmake .
- make
- scripts/start_db.sh
- sudo ln -s $TRAVIS_BUILD_DIR/etc/dcomp /etc/dcomp
- dcomp daemon &
- dcompestd  &
- dcompauthd  &
- sed "s/^dockerhost:.*/dockerhost: unix:\/\/\/var\/run\/docker.sock/" -i /etc/dcomp/plugins/local/local.yaml
- dcomplocalpd &
- dcompdmd /etc/dcomp/plugins/local/dmd.yaml &


script:
- go test ./...
- python Tests/test.py