daemon:
 addr: :8007
 key: blabla
 certfile: /etc/dcomp/cert/certauth.pem
 keyfile: /etc/dcomp/cert/keyauth.pem
ldap:
  host: it-ldap-slave01.desy.de:1389
  basedn: ou=rgy,o=DESY,c=DE
tokenduration: 120
authorization:
  - Basic
  - Negotiate
  - None


